# This Deployment manifest defines:
# - single-replica deployment of the container image, with label "app: python-hello-world"
# - Pod exposes port 8080
# - specify PORT environment variable to the container process
# Syntax reference https://kubernetes.io/docs/concepts/configuration/overview/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-ig-lightworker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-ig-lightworker
  template:
    metadata:
      labels:
        app: dev-ig-lightworker
    spec:
      containers:
      - name: server
        image: dev-ig-lightworker
        ports:
        - containerPort: 9092
        env:
        - name: PORT
          value: "9092"
        resources: {}
        tty: true
      restartPolicy: Always
status: {}